# Generated by Django 4.2.24 on 2025-10-07 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10)),
                ('tipo_refeicao', models.CharField(choices=[('cafe', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar')], max_length=10)),
                ('descricao', models.TextField(verbose_name='Alimentos ou Refeição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana', 'tipo_refeicao'],
                'unique_together': {('usuario', 'dia_semana', 'tipo_refeicao')},
            },
        ),
    ]
