# Generated by Django 4.2.24 on 2025-10-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoalimentar',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
