# Generated by Django 4.2.25 on 2025-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_planoalimentar_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoalimentar',
            name='calorias',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Calorias'),
        ),
    ]
