version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=meubanco
      - POSTGRES_USER=meuusuario
      - POSTGRES_PASSWORD=minhasenha
    ports:
      - "5432:5432"

  # Serviço da Aplicação Web Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=meubanco
      - POSTGRES_USER=meuusuario
      - POSTGRES_PASSWORD=minhasenha
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: